'use client';
import {useEffect,useRef} from 'react';
import {Leva,useControls,folder,button} from 'leva';
import Stats from 'stats-gl';
import {tiers,type Tier} from './tiers';
import {startHomeIntro} from '@/lib/home-intro';
import {transitionTo,type RoutePreset} from '@/lib/route-transition';
import {scene,tuning,type Tuning} from '@/lib/scene-store';
import {capabilityTuning} from '../formations/capability-systems';
import {pointerProfiles} from '../interaction/profiles';
const devTransition={preset:'work' as RoutePreset};
export default function DevTools(){const output=useRef<HTMLPreElement>(null);
 const number=(key:keyof Tuning,min:number,max:number,step:number,geometry=false)=>({value:tuning[key] as number,min,max,step,onChange:(value:number)=>{Object.assign(tuning,{[key]:value});if(geometry)window.dispatchEvent(new Event('asl:geometry'));}});
 const capability=(key:keyof typeof capabilityTuning,min:number,max:number,step:number)=>({value:capabilityTuning[key],min,max,step,onChange:(value:number)=>{capabilityTuning[key]=value;window.dispatchEvent(new Event('asl:geometry'));}});
 useControls({
 'Scene':folder({state:{value:'SCROLL',options:['SCROLL','EMERGENCE','FILAMENTS','CLOUD','DNA','ASL'],onChange:(value:string)=>{scene.manual=value!=='SCROLL';const states:Record<string,number>={EMERGENCE:0,FILAMENTS:.06,CLOUD:.235,DNA:.397,ASL:.515};scene.sectionPreview='';if(scene.manual){scene.sceneProgress=states[value];scene.homeIntro=value==='EMERGENCE'?0:1;}}},openingScreens:{value:4,min:3,max:4.5,step:.5,onChange:(value:number)=>{tuning.openingScreens=value;window.dispatchEvent(new Event('resize'));}},manual:{value:false,onChange:(v:boolean)=>{scene.manual=v;}},sceneProgress:{value:0,min:0,max:1,step:.001,onChange:(v:number)=>{if(scene.manual)scene.sceneProgress=v;}},tier:{value:'auto',options:['auto','high','medium','low'],onChange:(v:string)=>{tuning.tier=v;if(v!=='auto')tuning.count=tiers[v as Tier].count;window.dispatchEvent(new Event('asl:geometry'));}},count:number('count',18000,100000,1000,true)}),
 'Entry / intro':folder({
  homeEntry:button(()=>window.dispatchEvent(new CustomEvent('asl:entry-replay',{detail:'home'}))),
  innerEntry:button(()=>window.dispatchEvent(new CustomEvent('asl:entry-replay',{detail:'inner'}))),
  replayEmergence:button(()=>{scene.manual=true;scene.sceneProgress=0;startHomeIntro();}),
  entryDebug:{value:false,onChange:(v:boolean)=>{scene.entryDebug=v;}},
  entryProgress:{value:0,min:0,max:1,step:.01,onChange:(v:number)=>{if(scene.entryDebug)scene.entryProgress=v;}},
  bypassEntry:button(()=>{document.querySelector<HTMLButtonElement>('.entry-skip')?.click();}),
  homeIntro:{value:0,min:0,max:1,step:.01,onChange:(v:number)=>{if(scene.manual)scene.homeIntro=v;}},
  heroProgress:{value:0,min:0,max:1,step:.001,onChange:(v:number)=>{if(scene.manual)scene.sceneProgress=v*.52;}},
 },{collapsed:true}),
 'Route transition':folder({preset:{value:'work',options:['home','work','project','capabilities','about','contact'],onChange:(v:string)=>{devTransition.preset=v as RoutePreset;}},preview:button(()=>transitionTo(devTransition.preset)),routeProgress:{value:1,min:0,max:1,step:.01,onChange:(v:number)=>{if(scene.manual){scene.routeProgress=v;scene.routeMix=Math.sin(v*Math.PI);}}}},{collapsed:true}),
 'Section previews':folder({formation:{value:'NONE',options:['NONE','DESIGN_MEMBRANE','DEVELOPMENT_LAMELLAE','DEPLOYMENT_RIBBONS','PRODUCT_OPEN_SHELL','DESIGN_LATTICE','DESIGN_SURFACE','DEVELOPMENT_STRATA','DEVELOPMENT_FRAME','DEPLOYMENT_WAVE','DEPLOYMENT_STREAM','PRODUCT_CLUSTER','PRODUCT_SHELL'],onChange:(v:string)=>{scene.sectionPreview=v==='NONE'?'':v;if(v!=='NONE'){scene.manual=true;scene.homeIntro=1;scene.sceneProgress=v.startsWith('DESIGN')?.60:v.startsWith('DEVELOPMENT')?.68:v.startsWith('DEPLOYMENT')?.76:.85;window.dispatchEvent(new Event('asl:geometry'));}}},strength:number('sectionStrength',0,1,.05)},{collapsed:true}),
 'Capabilities - Design':folder({pathCount:capability('pathCount',4,12,1),weaveStrength:capability('weaveStrength',0,1.5,.05),curvature:capability('curvature',0,2,.05),depthSpread:capability('depthSpread',.2,2,.05),tension:capability('tension',0,1,.05)},{collapsed:true}),
 'Capabilities - Development':folder({nodeCount:capability('nodeCount',3,6,1),connectionDensity:capability('connectionDensity',.4,1,.05),depth:capability('architectureDepth',.2,2,.05),structuralAlignment:capability('alignment',0,1,.05)},{collapsed:true}),
 'Capabilities - Deployment':folder({propagationSpeed:capability('propagationSpeed',0,1,.05),frontWidth:capability('frontWidth',.05,.5,.01),streamCount:capability('streamCount',3,10,1),spread:capability('propagationSpread',.4,1.5,.05),depth:capability('propagationDepth',.2,2,.05)},{collapsed:true}),
 'Capabilities - Products':folder({moduleCount:capability('moduleCount',3,6,1),moduleRadius:capability('moduleRadius',.5,1.5,.05),connectionStrength:capability('connectionStrength',.1,1,.05),synchronisation:capability('synchronisation',0,1,.05),spatialSpread:capability('spatialSpread',.6,1.2,.05)},{collapsed:true}),
 'Particle character':folder({coreSize:number('coreSize',.25,.8,.01),falloffSize:number('falloffSize',.3,1,.02),brightness:number('particleBrightness',.2,2,.05),opacity:number('particleOpacity',.2,1,.02),densityResponse:number('densityResponse',.5,1.5,.02),pointSize:number('pointSize',.5,4,.1),sizeDistribution:number('sizeDistribution',.2,2,.1),largeShare:number('largeShare',0,.02,.001),focalDistance:number('focalDistance',4,16,.1),blur:number('blur',0,2,.05),stretch:number('stretch',0,2,.1),twinkle:number('twinkle',0,.5,.01),idleNoise:number('idleNoise',0,.5,.01),curvature:number('curvature',0,2,.05)},{collapsed:true}),
 'Formations':folder({cloudDensity:number('cloudDensity',.2,1.5,.05,true),cloudSpread:number('cloudSpread',.5,1.5,.05,true),helixRadius:number('helixRadius',.5,1.5,.05,true),helixLength:number('helixLength',.5,1.3,.05,true),helixTwist:number('helixTwist',-3.14,3.14,.05,true),helixYaw:number('helixYaw',-.6,.6,.02,true),helixPitch:number('helixPitch',-.3,.3,.01,true),helixRoll:number('helixRoll',-.2,.2,.01,true),helixVariation:number('helixVariation',0,.3,.01,true),cameraDepth:number('cameraDepth',-2,1.5,.1,true),helixOffset:number('helixOffset',-2,2,.1,true),helixDepth:number('helixDepth',.3,1.5,.05,true),helixTurns:number('helixTurns',1,3,.1,true),filamentCount:number('filamentCount',5,9,1,true),filamentSpread:number('filamentSpread',.5,2,.05,true),filamentDepth:number('filamentDepth',.3,1.5,.1,true),braid:number('braid',0,1,.05,true),surfaceFold:number('surfaceFold',.2,1.5,.05,true),surfaceTwist:number('surfaceTwist',0,2,.1,true),surfaceDepth:number('surfaceDepth',.3,1.5,.1,true),surfaceScale:number('surfaceScale',.5,1.2,.05,true),logoScale:number('logoScale',.6,1.5,.05,true)},{collapsed:true}),
 'Environment':folder({dprCap:number('dprCap',1,2,.25,true),materialIntensity:{value:tuning.materialIntensity,min:0,max:.6,step:.02,onChange:(v:number)=>{tuning.materialIntensity=v;document.documentElement.style.setProperty('--material-intensity',String(v));}},contamination:{value:tuning.contamination,min:0,max:.4,step:.02,onChange:(v:number)=>{tuning.contamination=v;document.documentElement.style.setProperty('--material-contamination',String(v));}},lightStrength:{value:tuning.lightStrength,min:0,max:.3,step:.01,onChange:(v:number)=>{tuning.lightStrength=v;document.documentElement.style.setProperty('--material-light',String(v));}},ambientDensity:number('ambientDensity',0,1.65,.05,true),ambientBrightness:number('ambientBrightness',0,.25,.01),ambientMovement:number('ambientMovement',0,3,.1),ambientDepth:number('ambientDepth',.3,2,.1,true),textureIntensity:{value:tuning.textureIntensity,min:0,max:.05,step:.002,onChange:(v:number)=>{tuning.textureIntensity=v;document.documentElement.style.setProperty('--texture-intensity',String(v));}}},{collapsed:true}),
 'Interaction':folder({enabled:{value:tuning.pointerEnabled,onChange:(v:boolean)=>{tuning.pointerEnabled=v;}},radiusPx:number('pointerRadius',30,180,2),pointerStrength:number('pointerStrength',0,1.5,.05),falloffSoftness:number('pointerFalloff',.5,3,.05),depthDisplacement:number('pointerDepth',0,1.2,.05),recoverySpeed:number('recovery',7,16,.25),velocityInfluence:number('velocityInfluence',0,.5,.02)},{collapsed:true}),
 'Per-state pointer':folder(Object.fromEntries(Object.entries(pointerProfiles).map(([name,profile])=>[name,folder(Object.fromEntries(Object.entries(profile).map(([key,value])=>[`${name}_${key}`,{label:key,value,min:key==='recovery'?.65:0,max:1.5,step:.05,onChange:(v:number)=>{Object.assign(profile,{[key]:v});}}])),{collapsed:true})])),{collapsed:true}),
 });
 useEffect(()=>{const stats=new Stats({trackGPU:false,trackCPT:false});stats.dom.classList.add('dev-performance');stats.dom.style.cssText='position:fixed;bottom:0;left:0;top:auto;z-index:60';document.body.appendChild(stats.dom);let frame=0;const tick=()=>{stats.update();frame=requestAnimationFrame(tick);};tick();const id=setInterval(()=>{if(output.current)output.current.textContent=`${scene.state} | ${scene.fps} fps\nentry ${scene.entryProgress.toFixed(2)} | intro ${scene.homeIntro.toFixed(2)} | hero ${(scene.sceneProgress/.52).toFixed(2)}\nroute ${scene.routePreset} ${scene.routeProgress.toFixed(2)}\n${scene.count} main + ${scene.ambient} ambient | DPR ${scene.dpr}\nProjected target bounds (unclipped W Ã- H):\n`+Object.entries(scene.bounds).map(([k,v])=>`${k}: ${v.width}% Ã- ${v.height}%`).join('\n');},500);
 const api={scene,tuning,pointerProfiles,transitionTo,startHomeIntro,replayEntry:(kind:string)=>window.dispatchEvent(new CustomEvent('asl:entry-replay',{detail:kind})),rebuild:()=>window.dispatchEvent(new Event('asl:geometry'))};Object.assign(window,{__ASL:api});return()=>{clearInterval(id);cancelAnimationFrame(frame);stats.dom.remove();Reflect.deleteProperty(window,'__ASL');};},[]);
 return <div className="dev-tools"><Leva collapsed/><details className="dev-readout"><summary>Scene measurements</summary><pre ref={output}/></details></div>;
}
