'use client';
import {useEffect} from 'react';
import {usePathname} from 'next/navigation';
import gsap from 'gsap';
import {scene} from '@/lib/scene-store';
export function SceneEnvironment(){const path=usePathname();useEffect(()=>{const css=getComputedStyle(document.documentElement);const colors=Object.fromEntries(['--color-void','--color-ink','--color-wine','--color-burgundy'].map(name=>[name,css.getPropertyValue(name).trim()]));const color=(name:string)=>colors[name];const layer=document.querySelector('.canvas-layer');const header=document.querySelector('.site-header');const home=path==='/'||path==='/lab/mutable-matter';document.documentElement.dataset.page=home?'home':'inner';
 const update=()=>{const p=scene.sceneProgress;let background=color('--color-void');if(p>.52)background=gsap.utils.interpolate(color('--color-void'),color('--color-ink'),Math.min(1,(p-.52)/.06));if(p>.92)background=gsap.utils.interpolate(color('--color-ink'),color('--color-wine'),Math.min(1,(p-.92)/.08));if(path==='/about')background=color('--color-burgundy');if(scene.routeActive){let source=scene.routeFromPreset==='contact'?color('--color-wine'):scene.routeFromPreset==='about'?color('--color-burgundy'):scene.routeFrom>.52?color('--color-ink'):color('--color-void');if(scene.routeEntry)source=color('--color-void');background=gsap.utils.interpolate(source,background,scene.routeProgress);}document.documentElement.dataset.identity=scene.routeMix>0?'transition':'rest';if(scene.fallback&&path==='/contact')background=color('--color-wine');gsap.set(layer,{backgroundColor:background});const statementMix=scene.routeMix>0?0:home?gsap.utils.clamp(0,1,(p-.86)/.05)*(1-gsap.utils.clamp(0,1,(p-.92)/.045)):path==='/about'?1:0;const capWarm=home?Math.max(0,1-Math.abs(p-.68)/.08)*.62+Math.max(0,1-Math.abs(p-.85)/.08)*.4:0;
 const warm=Math.min(1,Math.max(capWarm,statementMix));
 document.documentElement.style.setProperty('--material-presence',String(scene.fallback?1:gsap.utils.clamp(0,1,(p-.51)/.07)));
 document.documentElement.style.setProperty('--material-shift',`${(p-.5)*(scene.reduced?1:5)}%`);
 if(home&&p>.52&&p<.92){background=gsap.utils.interpolate(background,color('--color-burgundy'),warm*.75);gsap.set(layer,{backgroundColor:background});}
 const headerColor=gsap.utils.interpolate(background,color('--color-burgundy'),statementMix);(header as HTMLElement|null)?.style.setProperty('--header-surface',headerColor);document.documentElement.dataset.stage=p>.52&&p<.86?'capabilities':p>=.92?'final':'opening';};gsap.ticker.add(update);return()=>{gsap.ticker.remove(update);};},[path]);return null;}
